---
- name: ensure redis container is running
  docker: image=crosbymichael/redis name=redis 
  tags: docker

- name: ensure redis_ambassador container is running
  docker: image=svendowideit/ambassador expose=6379 ports=6379:6379 links=redis:redis name=redis_ambassador_ansible
  tags: docker



